version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3000" 

  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3000"  

  mongo:
    image: mongo
    ports:
      - "27017:27017"  
